use_frameworks!

platform :ios, '12.0'

target 'GXVersionUpdateView_Example' do
  pod 'GXVersionUpdateView', :path => '../'

  target 'GXVersionUpdateView_Tests' do
    inherit! :search_paths

    
  end
end
